#!/usr/bin/env bash

set -e

if [ -z $CC ]; then
  CC=$(command -v clang || echo gcc)
fi
if ! command -v "$CC" >/dev/null; then
  echo "'$CC' not found. Install 'clang' or 'gcc' or set \$CC to the C compiler executable."
  exit 1
fi

mkdir -p obj bin

extra_opts=""

if [ ${OPTIMIZE:-1} -ne 0 ]; then
  extra_opts="-O3 -DRELEASE"
else
  extra_opts="-g"
fi

if [ ${ALWAYS_PERSIST_SEARCH_HISTORY:-0} -ne 0 ]; then
  extra_opts="$extra_opts -DALWAYS_PERSIST_SEARCH_HISTORY"
fi

if [ ${FULL_REBUILD:-0} -ne 0 -o ! -e obj/stb.o ]; then
  echo "Building obj/stb.o"
  $CC -std=c11 -O3 -c -o obj/stb.o lib/stb.c
fi

ld -r -b binary data/DejaVuSans.ttf -o obj/font.o

$CC $extra_opts -std=c11 -Wshadow -pthread -I. -o i2x obj/stb.o obj/font.o src/main.c -lm -lX11 -lGL -lGLX -lXi

if [ ${OPTIMIZE:-1} -ne 0 ]; then
  strip i2x
fi
